#!/usr/bin/env bash
# Generate TypeScript types from JSON Schemas into packages/node/src/.
# Generated files have a "DO NOT EDIT" banner.
set -euo pipefail

cd "$(dirname "$0")/.."

OUT_DIR="packages/node/src"
mkdir -p "$OUT_DIR"

generate() {
  local schema=$1
  local out=$2
  echo "==> Generating $out from $schema"
  npx json-schema-to-typescript "$schema" \
    --bannerComment "/* eslint-disable */
/**
 * DO NOT EDIT. This file is generated by scripts/generate-node-types.sh.
 * Source: $schema
 */" \
    > "$out"
}

generate schemas/event-envelope.json   "$OUT_DIR/envelope.ts" EventEnvelope
generate schemas/problem-details.json  "$OUT_DIR/problem.ts"  ProblemDetails

echo "Done. Generated files:"
ls -la "$OUT_DIR"
