/* eslint-disable */
/**
 * DO NOT EDIT. This file is generated by scripts/generate-node-types.sh.
 * Source: schemas/event-envelope.json
 */

/**
 * Shared envelope for every event published to the logistics.events exchange.
 */
export interface EventEnvelope {
  /**
   * Globally unique id for this event instance.
   */
  eventId: string;
  /**
   * Dotted event type, matches the RabbitMQ routing key.
   */
  eventType: string;
  /**
   * Schema version of the event payload. Additive changes bump minor.
   */
  eventVersion: string;
  occurredAt: string;
  /**
   * Propagated from the originating X-Request-Id.
   */
  correlationId: string;
  /**
   * Name of the producing service (e.g., order-service).
   */
  producer: string;
  /**
   * Event-specific payload. Validated against the eventType+eventVersion.
   */
  data: {
    [k: string]: unknown;
  };
}
