/* eslint-disable */
/**
 * DO NOT EDIT. This file is generated by scripts/generate-node-types.sh.
 * Source: schemas/problem-details.json
 */

/**
 * RFC 7807 problem details. Returned by every service for error responses.
 */
export interface ProblemDetails {
  /**
   * A URI reference identifying the problem type.
   */
  type: string;
  /**
   * Short, human-readable summary of the problem type.
   */
  title: string;
  status: number;
  /**
   * Human-readable explanation specific to this occurrence.
   */
  detail?: string;
  /**
   * A URI reference identifying the specific occurrence.
   */
  instance?: string;
  requestId?: string;
  /**
   * Per-field validation errors when applicable.
   */
  errors?: {
    field: string;
    message: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
